### ISSUE TITLE
在某些平台上，SDK丢失了RequestId

### ISSUE THREAD

**Issue by red-chen** [aliyun/aliyun-tablestore-go-sdk#19]
map[X-Ots-Requestid:[0005698d-9dce-b347-0cc3-980a09c33ec8] X-Ots-Contenttype:[protocol buffer] X-Ots-Date:[2018-04-11T07:30:42.430654Z] Date:[Wed, 11 Apr 2018 07:30:42 GMT] Connection:[keep-alive] Authorization:[OTS *************] X-Ots-Contentmd5:[TzgBb4fK4cxD8Ldjw4JGHQ==]]

显示通过x-ots-requestid  拿数据失败

**Comment by red-chen** [comment]
应该在tablestore/model.go中拿到Response时，显示的将Header转换为小写

diff --git a/tablestore/model.go b/tablestore/model.go
index 909661a..2503ab4 100644
--- a/tablestore/model.go
+++ b/tablestore/model.go
@@ -42,7 +42,20 @@ type IHttpClient interface {
 }
 
 func (httpClient *TableStoreHttpClient) Do(req *http.Request) (*http.Response, error) {
-       return httpClient.httpClient.Do(req)
+       var resp *http.Response
+       var err error
+
+       if resp, err = httpClient.httpClient.Do(req); err != nil {
+               return nil, err
+       }
+
+       for k, v := range resp.Header {
+               nk := strings.ToLower(k)
+               delete(resp.Header, k)
+               resp.Header[nk] = v
+       }
+
+       return resp, nil
 }
 
 func (httpClient *TableStoreHttpClient) New(client *http.Client) {

**Comment by danielxiaoran** [comment]
fixed
