### ISSUE TITLE
BatchGetRow bug

### ISSUE THREAD

**Issue by SeTriones** [aliyun/aliyun-tablestore-go-sdk#3]
当BatchGetRow中某个表的某个主键不存在时，会返回unexpect io end

在ots的文档中说到（https://help.aliyun.com/document_detail/27310.html?spm=5176.doc52265.6.615.NDnOUA）：
如果某行不存在或者某行在指定的 columns_to_get 下没有数据，仍然会在 TableInBatchGetRowResponse 中有一条对应的 RowInBatchGetRowResponse，但其 row 下面的 primary_key_columns 和 attribute_columns 将为空。

unexpect io end应该就是读到了空的primary_key_columns 和 attribute_columns。
应该判断一下错误类型，而不是直接返回unexpect io end。

**Comment by danielxiaoran** [comment]
感谢反馈，会尽快更新你提到的问题

**Comment by danielxiaoran** [comment]
sdk 已经更新，问题已经修复。
