### ISSUE TITLE
TmLine.scan 返回数据无序

### ISSUE THREAD

**Issue by miraclew** [aliyun/aliyun-tablestore-go-sdk#45]
使用TmLine.scan 获取timeline的数据，发现是无序的。
看了一下SDK的代码timeline/store.go返回的是一个map， timeline.go中的asyncScan直接循环获取map中k,v 导致结果无序

**Comment by zhoucan1990** [comment]
感谢反馈，会提供一个新的接口，返回sequenceID顺序的data slice，也欢迎提PR！

**Comment by zhoucan1990** [comment]
#55

**Comment by zhoucan1990** [comment]
@miraclew 已经ci，感谢指出问题！
