### ISSUE TITLE
这个垃圾SDK到底能不能用

### ISSUE THREAD

**Issue by miraclew** [aliyun/aliyun-tablestore-go-sdk#54]
timeline 中的Scan函数，MaxCount参数没用，返回数据也无序。这种基本的问题(几行代码搞定)为何迟迟没人解决？？用户怎么使用？？

#45  
#48

**Comment by zhoucan1990** [comment]
抱歉，[#45](https://github.com/aliyun/aliyun-tablestore-go-sdk/issues/45) 这个问题还没来得及改，我会尽快把现在默认store实现的Scan置为Deprecated，然后提供一个SequencialScan接口保证顺序的。
#48 MaxCount现在在timeline.Api也是有用的，因为asyncScan中有在检查MaxCount，不过透传到criteria是更严谨的做法，感谢@lqvito !

**Comment by xinz** [comment]
@miraclew 遇到问题可以提交PR进行改进，而不是这样进行没意义的吐槽，难道因为这是阿里云官方团队在维护的sdk项目，所以可以这样肆意“吐槽”？即使你是付费用户，也请尊重开源项目及维护者。

**Comment by miraclew** [comment]
感谢 @zhoucan1990 修复 MaxCount的问题。由于项目已经依赖tablestore了，现在有点骑虎难下了，抱歉，激动了。希望系统sdk尽快完善。
