### ISSUE TITLE
Bug - Panic when query multiple rows by partition key

### ISSUE THREAD

**Issue by jzhang28** [aliyun/aliyun-tablestore-go-sdk#69]
Two primary keys: ProdId string, CommentId int64 (NOT incremental)

When query multiple rows by ProdId, with Min and Max of CommentId, panic when kicks off query

func GetMultiComments(prodId string) (*tablestore.GetRangeResponse, error) {

	fmt.Println("batch get row started")

	rangeRowQueryCriteria := &tablestore.RangeRowQueryCriteria{}
	rangeRowQueryCriteria.TableName = TableName

	startPK := new(tablestore.PrimaryKey)
	startPK.AddPrimaryKeyColumn("ProdId", prodId)
	startPK.AddPrimaryKeyColumnWithMinValue("CommentId")

	endPK := new(tablestore.PrimaryKey)
	endPK.AddPrimaryKeyColumn("ProdId", prodId)
	endPK.AddPrimaryKeyColumnWithMaxValue("CommentId")

	rangeRowQueryCriteria.StartPrimaryKey = startPK
	rangeRowQueryCriteria.EndPrimaryKey = endPK
	rangeRowQueryCriteria.MaxVersion = 1
	rangeRowQueryCriteria.Limit = 1
	rangeRowQueryCriteria.Direction = tablestore.FORWARD

	getRangeRequest := &tablestore.GetRangeRequest{}
	getRangeRequest.RangeRowQueryCriteria = rangeRowQueryCriteria

	client := CreateClient()
	getRangeResp, err := client.GetRange(getRangeRequest)	//panic

	return getRangeResp, err
}

I refer to below SDK example:
https://github.com/aliyun/aliyun-tablestore-go-sdk/blob/master/sample/MultipleRowOperation.go
https://help.aliyun.com/document_detail/52265.htm

**Comment by jzhang28** [comment]
![reproduce error](https://user-images.githubusercontent.com/8264029/77609584-97b0de00-6edd-11ea-8102-44190742727a.png)
Panic error is attached.

**Comment by zhoucan1990** [comment]
I replaced code line 100 'client := CreateClient()' with 'client := tablestore.NewClient(...)', then this code snippet works fine without panic. Can you provide more panic error stack in tablestore sdk?

**Comment by jzhang28** [comment]
I figured out the solution. The data type of commentId I defined is incorrect which must be INT64.
