### ISSUE TITLE
条件更新

### ISSUE THREAD

**Issue by phantomlsh** [aliyun/aliyun-tablestore-go-sdk#85]
针对官方文档提供的条件更新接口：https://help.aliyun.com/document_detail/35194.html

请问此SDK有封装这个接口吗？能否提供一个代码案例？

谢谢

**Comment by xinz** [comment]
类似的使用方法可以参考：https://github.com/aliyun/aliyun-tablestore-go-sdk/blob/master/sample/SingleRowOperation.go#L69
